### ISSUE TITLE
Big Ten Two-Zone Homogenized Benchmark  IEU-MET-FAST-007

### ISSUE THREAD

**Issue by shajibGSL** [mit-crpg/benchmarks#35]
In MCNP the microbody RCC is used. What is the conversion of OpenMC surface? Thanks.

**Comment by paulromano** [comment]
The RCC macrobody is just a finite cylinder, The particular example you have here could be done with a z-cylinder and two z-planes, so something like:
```xml
<surface id="1" type="z-cylinder" coeffs="0. 0. 26.67" />
<surface id="2" type="z-plane" coeffs="-28.8169" />
<surface id="3" type="z-plane" coeffs="28.8160" />
...
<cell id="1" region="-1 2 -3" ... />
...
```

**Comment by shajibGSL** [comment]
Hello, I make the changes accordingly 

<?xml version="1.0"?>
<geometry>

    <cell id="1" material="1" region="-1 3 -4" /> 
    <cell id="2" material="2" region=" -2  5 -6 1 -3 4" /> 

    <surface id="1" type="z-cylinder" coeffs="0. 0. 26.67" />
    <surface id="2" type="z-cylinder" coeffs="0. 0. 41.91" boundary="vacuum" />
    <surface id="3" type="z-plane" coeffs="-28.8169" />
    <surface id="4" type="z-plane" coeffs="28.8169" />
    <surface id="5" type="z-plane" coeffs="-48.2600" />
    <surface id="6" type="z-plane" coeffs="48.2600" />

</geometry>

But now I get  ERROR: Maximum number of lost particles has been reached when my settings.xml is 

<?xml version="1.0"?>
<settings>
    
    
    <run_mode>eigenvalue</run_mode>
    <batches>50</batches>
    <inactive>5</inactive>
    <particles>1000</particles>
    
    
    <source>
        <space type="box" parameters="-1  -1  -1  1  1  1" />
    </source>
    
</settings>

Also my material file is 

<?xml version="1.0"?>
<materials>
    
    <material id="1">
        <density units="sum" />
        <nuclide name="U234" ao="2.4761e-05" />
        <nuclide name="U235" ao="4.8461e-03" />
        <nuclide name="U236" ao="4.3348e-05" />
        <nuclide name="U238" ao="4.2695e-02" />
    </material>

    
    <material id="2">
        <density units="sum" />
        <nuclide name="U234" ao="2.8672e-07" />
        <nuclide name="U235" ao="1.0058e-04" />
        <nuclide name="U236" ao="1.1468e-06" />
        <nuclide name="U238" ao="4.7677e-02" />
    </material>
</materials>

either way, I put boundary for surface 2 to "reflective" or "vacuum" the same result. Thanks.

**Comment by paulromano** [comment]
You need to have boundary conditions on the top and bottom z-planes as well. Otherwise particles reach them and can't find anything on the other side (hence they are lost).

By the way, this repository is not a great place to ask these kinds of questions. I'd encourage to send questions like this to the OpenMC [user's group mailing list](https://groups.google.com/forum/#!forum/openmc-users) instead.

**Comment by shajibGSL** [comment]
Thank you Paul Romano for your guide. Thanks for giving me the group mailing list. I also work on developer support for a company, and I know this is irritating. I am on my master's degree in Nuclear engineering. I find your repository greatly helpful. Thank you, bro.
