### ISSUE TITLE
Big Ten Two-Zone Homogenized Benchmark IEU-MET-FAST-007

### ISSUE THREAD

**Issue by shajibGSL** [mit-crpg/benchmarks#36]
Why do I get  ERROR: Maximum number of lost particles has been reached. Please reply.

    <cell id="1" material="1" region="-1 3 -4" /> 
    <cell id="2" material="2" region=" -2  5 -6 1 -3 4" /> 

    <surface id="1" type="z-cylinder" coeffs="0. 0. 26.67" />
    <surface id="2" type="z-cylinder" coeffs="0. 0. 41.91" boundary="vacuum" />
    <surface id="3" type="z-plane" coeffs="-28.8169" />
    <surface id="4" type="z-plane" coeffs="28.8169" />
    <surface id="5" type="z-plane" coeffs="-48.2600" />
    <surface id="6" type="z-plane" coeffs="48.2600" />

material is 

    
    <material id="1">
        <density units="sum" />
        <nuclide name="U234" ao="2.4761e-05" />
        <nuclide name="U235" ao="4.8461e-03" />
        <nuclide name="U236" ao="4.3348e-05" />
        <nuclide name="U238" ao="4.2695e-02" />
    </material>

    
    <material id="2">
        <density units="sum" />
        <nuclide name="U234" ao="2.8672e-07" />
        <nuclide name="U235" ao="1.0058e-04" />
        <nuclide name="U236" ao="1.1468e-06" />
        <nuclide name="U238" ao="4.7677e-02" />
    </material>

and setting is 

    
    
    <run_mode>eigenvalue</run_mode>
    <batches>50</batches>
    <inactive>5</inactive>
    <particles>1000</particles>
    
    
    <source>
        <space type="box" parameters="-1  -1  -1  1  1  1" />
    </source>

**Comment by paulromano** [comment]
Response given in #35
